import js from '@eslint/js';
import tseslint from 'typescript-eslint';

/**
 * Lint configuration.
 *
 * Type checking is `tsc`'s job and runs separately as `pnpm typecheck`, so this
 * uses the non-type-checked preset: linting the whole monorepo against a type
 * programme would duplicate that work and roughly triple the time it takes.
 *
 * The rules that are switched on beyond the recommended set are the ones this
 * codebase's guarantees actually depend on — chiefly that an unmeasured value
 * must stay absent rather than becoming a zero, which `??` preserves and `||`
 * silently destroys.
 */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/out/**',
      '**/release/**',
      '**/target/**',
      // Generated by napi from the Rust sources; the Rust doc comments are the
      // place to fix anything wrong with it.
      'native/telemetry/index.js',
      'native/telemetry/index.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx,mts}'],
    rules: {
      // `0 || fallback` takes the fallback. Every rate in this application is
      // legitimately zero, and an absent one is explicitly `undefined`, so
      // conflating the two would turn "not measured" into a measurement.
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      'no-restricted-syntax': [
        'error',
        {
          selector: "LogicalExpression[operator='||'] > Literal[value=0].right",
          message:
            'Use ?? rather than || when falling back to 0: a measured zero is not a missing value.',
        },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // The escape hatch out of the type system, in an application whose whole
      // claim is that its numbers mean what they say.
      '@typescript-eslint/no-explicit-any': 'error',
    },
  },
  {
    // Node-side scripts, which are plain JavaScript run directly.
    files: ['tools/**/*.mjs', 'eslint.config.mjs'],
    languageOptions: {
      // Listed explicitly rather than pulled from a globals package: these
      // scripts run on Node with no bundler, and this is the whole surface they
      // touch.
      globals: {
        Buffer: 'readonly',
        URL: 'readonly',
        WebSocket: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        process: 'readonly',
        setInterval: 'readonly',
        setTimeout: 'readonly',
      },
    },
  },
);
