/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The telemetry engine. One instance per application; owns the sampling thread. */
export declare class TelemetryEngine {
  constructor(config?: JsCollectorConfig | undefined | null)
  /**
   * Enable persistent history, writing to `path`.
   *
   * Nothing is created and nothing is written until this is called: a run
   * with history off must not touch the disk on the collector's account.
   */
  enableHistory(path: string): void
  /** Turn history off. Existing rows are left on disk. */
  disableHistory(): void
  /**
   * Read a window of history, choosing the finest tier that covers the span.
   *
   * Opens its own read-only connection rather than sharing the sampling
   * thread's: WAL mode means this cannot block a write, so the UI asking for
   * a week of data never stalls the sampler.
   */
  queryHistory(fromUnixMs: number, toUnixMs: number): JsHistoryResult
  /** Rows currently stored per tier, for the debug view. */
  historyTiers(): Array<JsHistoryTier>
  /**
   * Start sampling. `on_snapshot` is called on the JavaScript thread once per
   * interval. Calling `start` while already running is a no-op.
   */
  start(onSnapshot: (snapshot: JsSystemSnapshot) => void): void
  /** Stop sampling and join the thread. Safe to call when not running. */
  stop(): void
  get isRunning(): boolean
  /**
   * The panic that killed the sampling thread, or `null` if none did.
   *
   * Non-null means collection has stopped and every value the application is
   * showing is stale. It is a getter rather than an event because the
   * threadsafe function that would carry an event is exactly what stops
   * working when the sampler dies.
   */
  get collectorPanic(): string | null
  /** The most recent snapshot, or `null` before the first one completes. */
  getLatestSnapshot(): JsSystemSnapshot | null
  getConfig(): JsCollectorConfig
  /**
   * Apply a configuration change. The interval is clamped to a sane range and
   * the effective configuration is returned.
   */
  setConfig(config: JsCollectorConfig): JsCollectorConfig
}

/**
 * Collect exactly one snapshot without starting the engine.
 *
 * Every rate is unavailable in the returned snapshot because a single reading
 * of a cumulative counter carries no rate. Intended for diagnostics and tests,
 * not for polling.
 */
export declare function collectSingleSnapshot(): JsSystemSnapshot

/** Static information about the machine and our own privileges. */
export declare function getHostInfo(): JsHostInfo

export interface JsCollectionDiagnostics {
  totalDurationMs: number
  cpuDurationMs: number
  memoryDurationMs: number
  processDurationMs: number
  /** Disk, network and GPU together: they all read from one PDH query. */
  deviceDurationMs: number
  issues: Array<JsCollectorIssue>
  droppedSnapshots: number
  /**
   * Number of process identities the collector is tracking, so the
   * application can watch its own memory behaviour.
   */
  trackedProcessCount: number
}

export interface JsCollectorConfig {
  intervalMs: number
  collectProcesses: boolean
  collectDebug: boolean
  collectCommandLines: boolean
}

export interface JsCollectorIssue {
  subsystem: string
  code: string
  message: string
}

export interface JsCpuDebugSample {
  intervalMs: number
  idleDelta100ns: number
  kernelDelta100ns: number
  userDelta100ns: number
  totalDelta100ns: number
  busyDelta100ns: number
  getSystemTimes?: JsGetSystemTimesDelta
  counterCoverageRatio: number
  discarded: boolean
  discardReason?: string
  /** PDH counter paths that are actually registered on this machine. */
  pdhCounterPaths: Array<string>
}

export interface JsCpuSnapshot {
  aggregateTimeUtilizationPercent?: number
  processorUtilityPercent?: number
  processorPerformancePercent?: number
  pdhProcessorTimePercent?: number
  busiestLogicalProcessorPercent?: number
  busiestLogicalProcessorIndex?: number
  averageLogicalProcessorPercent?: number
  aggregateDpcPercent?: number
  aggregateInterruptPercent?: number
  currentFrequencyMhz?: number
  perLogicalProcessor: Array<JsLogicalProcessorSample>
  topology: JsCpuTopology
  processCount?: number
  threadCount?: number
  handleCount?: number
  uptimeMs?: number
  debug?: JsCpuDebugSample
}

export interface JsCpuTopology {
  packageCount: number
  physicalCoreCount: number
  logicalProcessorCount: number
  processorGroupCount: number
  logicalProcessorsPerGroup: Array<number>
  isHybrid: boolean
  efficiencyClasses: Array<number>
  brandString?: string
  baseFrequencyMhz?: number
}

export interface JsDiskSnapshot {
  /** PDH instance name, e.g. `0 C: D:`. */
  instance: string
  /** Physical disk number, when the instance name carried one. */
  index?: number
  /** Drive letters on this physical disk. */
  volumes: Array<string>
  readBytesPerSecond: number
  writeBytesPerSecond: number
  totalBytesPerSecond: number
  /** `100 - % Idle Time`, the basis Task Manager uses for "Active time". */
  activeTimePercent?: number
  averageReadLatencyMs?: number
  averageWriteLatencyMs?: number
  queueLength?: number
  readsPerSecond?: number
  writesPerSecond?: number
  /**
   * The drive's own sensor. Absent for the `_Total` aggregate and for any
   * device that does not implement the temperature property.
   */
  temperature?: JsTemperatureReading
}

export interface JsDisksSnapshot {
  disks: Array<JsDiskSnapshot>
  /** The `_Total` instance PDH synthesises, when present. */
  total?: JsDiskSnapshot
  /** True when the PhysicalDisk counter set could not be registered. */
  unavailable: boolean
}

export interface JsGetSystemTimesDelta {
  idleDelta100ns: number
  kernelDelta100ns: number
  userDelta100ns: number
  utilizationPercent: number
}

export interface JsGpuAdapterSnapshot {
  /** LUID key matching the PDH instance names, e.g. `0x00000000_0x000194b3`. */
  luid: string
  /** Adapter description from DXGI, absent when DXGI could not enumerate. */
  name?: string
  isSoftware: boolean
  /** Maximum across engine types - never a sum, because engines run concurrently. */
  utilisationPercent?: number
  engines: Array<JsGpuEngineSnapshot>
  dedicatedMemoryUsedBytes?: number
  dedicatedMemoryTotalBytes?: number
  sharedMemoryUsedBytes?: number
  sharedMemoryTotalBytes?: number
  /** Die temperature, when a vendor library reported one for this adapter. */
  temperature?: JsTemperatureReading
}

export interface JsGpuEngineSnapshot {
  /** Raw engine type from the counter, e.g. `3d`, `videodecode`. */
  engine: string
  /** Friendlier label for the same engine. */
  label: string
  utilisationPercent: number
}

export interface JsGpuSnapshot {
  adapters: Array<JsGpuAdapterSnapshot>
  /** True when the GPU counter sets could not be registered. */
  unavailable: boolean
}

export interface JsHistoryPoint {
  timestampUnixMs: number
  cpuTimePercent?: number
  cpuUtilityPercent?: number
  cpuBusiestPercent?: number
  memoryUsedBytes?: number
  memoryAvailableBytes?: number
  memoryCommittedBytes?: number
  diskReadBytesPerSecond?: number
  diskWriteBytesPerSecond?: number
  diskActivePercent?: number
  networkDownBytesPerSecond?: number
  networkUpBytesPerSecond?: number
  gpuPercent?: number
  gpuMemoryBytes?: number
  processCount?: number
  threadCount?: number
  handleCount?: number
  /** Peak within the window, which a mean would otherwise hide. */
  cpuTimePeakPercent?: number
  memoryUsedPeakBytes?: number
  diskTotalPeakBytesPerSecond?: number
}

export interface JsHistoryResult {
  points: Array<JsHistoryPoint>
  /** Which retention tier answered the query. */
  tier: number
  /** Nominal resolution of that tier, in milliseconds. */
  resolutionMs: number
  /** False when history is disabled or the database could not be opened. */
  available: boolean
}

export interface JsHistoryTier {
  tier: number
  rowCount: number
}

export interface JsHostInfo {
  computerName: string
  osName?: string
  osVersion: string
  osBuild?: string
  architecture: string
  isElevated: boolean
  hasDebugPrivilege: boolean
  bootTimeUnixMs?: number
  nativeModuleVersion: string
}

export interface JsLogicalProcessorSample {
  index: number
  group: number
  numberInGroup: number
  coreId?: number
  efficiencyClass?: number
  timeUtilizationPercent: number
  dpcPercent: number
  interruptPercent: number
  kernelPercent: number
  userPercent: number
  currentFrequencyMhz?: number
  maxFrequencyMhz?: number
}

export interface JsMemoryDebugGlobal {
  memoryLoadPercent: number
  totalPhysBytes: number
  availPhysBytes: number
  totalPageFileBytes: number
  availPageFileBytes: number
  totalVirtualBytes: number
  availVirtualBytes: number
}

export interface JsMemoryDebugList {
  freeAndZeroBytes: number
  modifiedBytes: number
  modifiedNoWriteBytes: number
  standbyBytes: number
  standbyByPriorityBytes: Array<number>
}

export interface JsMemoryDebugPerformance {
  pageSizeBytes: number
  commitTotalPages: number
  commitLimitPages: number
  commitPeakPages: number
  physicalTotalPages: number
  physicalAvailablePages: number
  systemCachePages: number
  kernelTotalPages: number
  kernelPagedPages: number
  kernelNonpagedPages: number
  handleCount: number
  processCount: number
  threadCount: number
}

export interface JsMemoryDebugSample {
  globalMemoryStatusEx: JsMemoryDebugGlobal
  performanceInformation?: JsMemoryDebugPerformance
  memoryList?: JsMemoryDebugList
  installedPhysicalBytes?: number
}

export interface JsMemorySnapshot {
  installedPhysicalBytes?: number
  totalPhysicalBytes: number
  availablePhysicalBytes: number
  usedPhysicalBytes: number
  physicalUtilizationPercent: number
  memoryLoadPercent: number
  committedBytes?: number
  commitLimitBytes?: number
  commitPeakBytes?: number
  cachedBytes?: number
  standbyBytes?: number
  modifiedBytes?: number
  freeBytes?: number
  pagedPoolBytes?: number
  nonPagedPoolBytes?: number
  pageFileTotalBytes?: number
  pageFileUsedBytes?: number
  pageSizeBytes: number
  debug?: JsMemoryDebugSample
}

export interface JsNetworkInterfaceSnapshot {
  name: string
  receivedBytesPerSecond: number
  sentBytesPerSecond: number
  totalBytesPerSecond: number
  linkSpeedBitsPerSecond?: number
  receivedPacketsPerSecond?: number
  sentPacketsPerSecond?: number
  outboundDiscardsPerSecond?: number
  isLoopback: boolean
}

export interface JsNetworkSnapshot {
  interfaces: Array<JsNetworkInterfaceSnapshot>
  /** Summed over non-loopback interfaces. */
  receivedBytesPerSecond: number
  sentBytesPerSecond: number
  unavailable: boolean
}

export interface JsProcessesSnapshot {
  processes: Array<JsProcessSnapshot>
  totalCount: number
  accessDeniedCount: number
  vanishedCount: number
  collectionDurationMs: number
}

export interface JsProcessSnapshot {
  /** `pid:createTime100ns`. The only safe identity across samples. */
  key: string
  pid: number
  parentPid: number
  parentKey?: string
  name: string
  imagePath?: string
  commandLine?: string
  /** Display only - exceeds the exact integer range of a JS number. */
  createTime100ns: number
  createTimeUnixMs: number
  sessionId: number
  isWow64?: boolean
  architecture?: string
  userName?: string
  isProtected?: boolean
  /** `ProductName` from the image version resource, e.g. "Google Chrome". */
  productName?: string
  /** `CompanyName` from the image version resource. */
  companyName?: string
  /** `FileDescription` from the image version resource. */
  fileDescription?: string
  /** Windows package full name, present only for packaged applications. */
  packageFullName?: string
  /** Application User Model ID, present only for packaged applications. */
  applicationUserModelId?: string
  basePriority: number
  kernelTime100ns: number
  userTime100ns: number
  cpuMachinePercent?: number
  cpuCoreEquivalentPercent?: number
  workingSetBytes: number
  privateWorkingSetBytes: number
  privateCommitBytes: number
  peakWorkingSetBytes: number
  pagedPoolBytes: number
  nonPagedPoolBytes: number
  virtualSizeBytes: number
  pageFaultCount: number
  hardFaultCount: number
  threadCount: number
  handleCount: number
  ioReadBytes: number
  ioWriteBytes: number
  ioOtherBytes: number
  ioReadOperations: number
  ioWriteOperations: number
  ioOtherOperations: number
  ioReadBytesPerSecond?: number
  ioWriteBytesPerSecond?: number
  /**
   * Maximum GPU engine utilisation for this process, 0..100. Absent when the
   * GPU counter set is unavailable or the process used no GPU.
   */
  gpuPercent?: number
  /** Dedicated (on-board) GPU memory attributed to this process. */
  gpuDedicatedMemoryBytes?: number
  /** Shared (system) GPU memory attributed to this process. */
  gpuSharedMemoryBytes?: number
  /**
   * Reason the handle-derived fields are missing, when they are.
   *
   * Declared with an explicit TypeScript union so the generated declaration
   * is as precise as the values we actually emit, and the published types can
   * be checked against it exactly.
   */
  detailFailure?: 'accessDenied' | 'processExited' | 'notSupported' | 'pending'
}

export interface JsSystemSnapshot {
  sequence: number
  wallClockUnixMs: number
  monotonicMs: number
  intervalMs?: number
  cpu: JsCpuSnapshot
  memory: JsMemorySnapshot
  processes?: JsProcessesSnapshot
  disks: JsDisksSnapshot
  network: JsNetworkSnapshot
  gpu: JsGpuSnapshot
  thermal: JsThermalSnapshot
  diagnostics: JsCollectionDiagnostics
}

export interface JsTemperatureReading {
  celsius: number
  /**
   * The source is what says how much the number can be trusted, so it
   * travels with every reading.
   *
   * Declared with an explicit `ts_type` so the generated declarations carry
   * the same union the published types do. A napi string enum would generate
   * a TypeScript `enum`, and a string literal is not assignable to an enum
   * member, which would break the bidirectional contract check in
   * `native-contract.ts` in one direction only - the worst kind of drift.
   */
  source: 'acpiThermalZone' | 'nvml' | 'storageDevice'
  /**
   * Exactly what reported it - an ACPI zone name, a GPU board name, a drive
   * model. Never a category such as "CPU".
   */
  sensor: string
  /** Where the vendor says throttling begins, when it publishes a threshold. */
  warningCelsius?: number
  /** Where the vendor says the device is in danger, when it publishes one. */
  criticalCelsius?: number
  /**
   * Age of the measurement. Zero for zone counters, read every sample; up to
   * the source's refresh interval for the ones polled more slowly.
   */
  measuredAgoMs: number
}

export interface JsThermalSnapshot {
  /** Every ACPI zone reporting a physically plausible value, hottest first. */
  zones: Array<JsThermalZoneSnapshot>
  /**
   * The hottest zone as a reading. **Not a CPU package temperature**: what an
   * ACPI zone is attached to is defined by the system firmware, so it is
   * always presented under its own zone name.
   */
  primaryZone?: JsTemperatureReading
  /**
   * Every GPU a vendor library reported, whether or not it could be joined to
   * an adapter.
   */
  gpus: Array<JsTemperatureReading>
  /** Every drive that reports a temperature. */
  drives: Array<JsTemperatureReading>
  /**
   * True when the `Thermal Zone Information` counter set is absent, which is
   * normal on a machine whose firmware declares no zones.
   */
  zonesUnavailable: boolean
  /** True when no NVIDIA driver is present. Not an error. */
  nvmlUnavailable: boolean
}

export interface JsThermalZoneSnapshot {
  /** The zone's ACPI name, e.g. `\_TZ.TZ01`. */
  instance: string
  celsius: number
  /** True when the value came from `High Precision Temperature`. */
  highPrecision: boolean
}

/** Confirms the native module loaded and reports its version. */
export declare function nativeProbe(): string

/**
 * Ask Windows to restart this application if it crashes or stops responding.
 *
 * `command_line` is what the restarted process receives, so pass a marker the
 * application can recognise. Returns false when Windows refused, which simply
 * means the application will not come back by itself.
 */
export declare function registerForRestart(commandLine: string): boolean

/**
 * Cancel the restart registration, so a deliberate quit is never mistaken for
 * a crash.
 */
export declare function unregisterForRestart(): boolean
