/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The telemetry engine. One instance per application; owns the sampling thread. */
export declare class TelemetryEngine {
  constructor(config?: JsCollectorConfig | undefined | null)
  /**
   * Enable persistent history, writing to `path`.
   *
   * Nothing is created and nothing is written until this is called: a run
   * with history off must not touch the disk on the collector's account.
   */
  enableHistory(path: string): void
  /** Turn history off. Existing rows are left on disk. */
  disableHistory(): void
  /**
   * Read a window of history, choosing the finest tier that covers the span.
   *
   * Opens its own read-only connection rather than sharing the sampling
   * thread's: WAL mode means this cannot block a write, so the UI asking for
   * a week of data never stalls the sampler.
   */
  queryHistory(fromUnixMs: number, toUnixMs: number): JsHistoryResult
  /** Rows currently stored per tier, for the debug view. */
  historyTiers(): Array<JsHistoryTier>
  /**
   * Start sampling. `on_snapshot` is called on the JavaScript thread once per
   * interval. Calling `start` while already running is a no-op.
   */
  start(onSnapshot: (snapshot: JsSystemSnapshot) => void): void
  /** Stop sampling and join the thread. Safe to call when not running. */
  stop(): void
  get isRunning(): boolean
  /**
   * The panic that killed the sampling thread, or `null` if none did.
   *
   * Non-null means collection has stopped and every value the application is
   * showing is stale. It is a getter rather than an event because the
   * threadsafe function that would carry an event is exactly what stops
   * working when the sampler dies.
   */
  get collectorPanic(): string | null
  /** The most recent snapshot, or `null` before the first one completes. */
  getLatestSnapshot(): JsSystemSnapshot | null
  getConfig(): JsCollectorConfig
  /**
   * Apply a configuration change. The interval is clamped to a sane range and
   * the effective configuration is returned.
   */
  setConfig(config: JsCollectorConfig): JsCollectorConfig
}

/**
 * Bring a process's front-most window forward, restoring it if minimised.
 *
 * Resolves to `done`, `noWindows`, `refused` when Windows would not move the
 * focus, `notRunning` or `identityChanged`.
 */
export declare function bringProcessToFront(key: string): JsActionOutcome

/**
 * Ask every taskbar window of a process to close, as its close button would.
 *
 * The program decides what happens next: it may close, ask to save, or ignore
 * the request. Resolves to `requested` with how many windows were asked,
 * `noWindows`, `accessDenied` when Windows would not deliver the request (the
 * program runs with higher privileges), `notRunning` or `identityChanged`.
 */
export declare function closeProcessWindows(key: string): JsActionOutcome

/**
 * Collect exactly one snapshot without starting the engine.
 *
 * Every rate is unavailable in the returned snapshot because a single reading
 * of a cumulative counter carries no rate. Intended for diagnostics and tests,
 * not for polling.
 */
export declare function collectSingleSnapshot(): JsSystemSnapshot

/**
 * Turn on SeDebugPrivilege, which a process running as administrator holds but
 * has switched off. True when it is on afterwards.
 */
export declare function enableDebugPrivilege(): boolean

/**
 * End a process and wait briefly to see it go.
 *
 * Resolves to `ended`, `stillExiting`, `critical` (refused: ending it would
 * stop Windows), `notRunning`, `identityChanged`, `accessDenied`, or `failed`
 * with the Windows error. Runs off the JavaScript thread, because the wait can
 * last seconds.
 */
export declare function endProcess(key: string): Promise<JsActionOutcome>

/** Static information about the machine and our own privileges. */
export declare function getHostInfo(): JsHostInfo

/** Read what the process menu may offer for a process. */
export declare function inspectProcess(key: string): JsProcessState

/** The result of an action. */
export interface JsActionOutcome {
  /** What happened. The possible values depend on the action. */
  outcome: 'ended' | 'stillExiting' | 'critical' | 'requested' | 'noWindows' | 'done' | 'refused' | 'notRunning' | 'identityChanged' | 'accessDenied' | 'failed'
  /** The Windows error code, when a call failed for a reason worth reporting. */
  win32Error?: number
  /** How many things the action touched, for the actions that touch several. */
  count?: number
}

export interface JsCollectionDiagnostics {
  totalDurationMs: number
  cpuDurationMs: number
  memoryDurationMs: number
  processDurationMs: number
  /** Disk, network and GPU together: they all read from one PDH query. */
  deviceDurationMs: number
  issues: Array<JsCollectorIssue>
  droppedSnapshots: number
  /**
   * Number of process identities the collector is tracking, so the
   * application can watch its own memory behaviour.
   */
  trackedProcessCount: number
}

export interface JsCollectorConfig {
  intervalMs: number
  collectProcesses: boolean
  collectDebug: boolean
  collectCommandLines: boolean
}

export interface JsCollectorIssue {
  subsystem: string
  code: string
  message: string
}

export interface JsCpuDebugSample {
  intervalMs: number
  idleDelta100ns: number
  kernelDelta100ns: number
  userDelta100ns: number
  totalDelta100ns: number
  busyDelta100ns: number
  getSystemTimes?: JsGetSystemTimesDelta
  counterCoverageRatio: number
  discarded: boolean
  discardReason?: string
  /** PDH counter paths that are actually registered on this machine. */
  pdhCounterPaths: Array<string>
}

export interface JsCpuSnapshot {
  aggregateTimeUtilizationPercent?: number
  processorUtilityPercent?: number
  processorPerformancePercent?: number
  pdhProcessorTimePercent?: number
  busiestLogicalProcessorPercent?: number
  busiestLogicalProcessorIndex?: number
  averageLogicalProcessorPercent?: number
  aggregateDpcPercent?: number
  aggregateInterruptPercent?: number
  aggregateKernelPercent?: number
  currentFrequencyMhz?: number
  perLogicalProcessor: Array<JsLogicalProcessorSample>
  topology: JsCpuTopology
  processCount?: number
  threadCount?: number
  handleCount?: number
  uptimeMs?: number
  debug?: JsCpuDebugSample
}

export interface JsCpuTopology {
  packageCount: number
  physicalCoreCount: number
  logicalProcessorCount: number
  processorGroupCount: number
  logicalProcessorsPerGroup: Array<number>
  isHybrid: boolean
  efficiencyClasses: Array<number>
  brandString?: string
  baseFrequencyMhz?: number
}

export interface JsDiskSnapshot {
  /** PDH instance name, e.g. `0 C: D:`. */
  instance: string
  /** Physical disk number, when the instance name carried one. */
  index?: number
  /** Drive letters on this physical disk. */
  volumes: Array<string>
  readBytesPerSecond: number
  writeBytesPerSecond: number
  totalBytesPerSecond: number
  /** `100 - % Idle Time`, the basis Task Manager uses for "Active time". */
  activeTimePercent?: number
  averageReadLatencyMs?: number
  averageWriteLatencyMs?: number
  queueLength?: number
  readsPerSecond?: number
  writesPerSecond?: number
  /**
   * The drive's own sensor. Absent for the `_Total` aggregate and for any
   * device that does not implement the temperature property.
   */
  temperature?: JsTemperatureReading
}

export interface JsDisksSnapshot {
  disks: Array<JsDiskSnapshot>
  /** The `_Total` instance PDH synthesises, when present. */
  total?: JsDiskSnapshot
  /** True when the PhysicalDisk counter set could not be registered. */
  unavailable: boolean
}

export interface JsGetSystemTimesDelta {
  idleDelta100ns: number
  kernelDelta100ns: number
  userDelta100ns: number
  utilizationPercent: number
}

export interface JsGpuAdapterSnapshot {
  /** LUID key matching the PDH instance names, e.g. `0x00000000_0x000194b3`. */
  luid: string
  /** Adapter description from DXGI, absent when DXGI could not enumerate. */
  name?: string
  isSoftware: boolean
  /** Maximum across engine types - never a sum, because engines run concurrently. */
  utilisationPercent?: number
  engines: Array<JsGpuEngineSnapshot>
  dedicatedMemoryUsedBytes?: number
  dedicatedMemoryTotalBytes?: number
  sharedMemoryUsedBytes?: number
  sharedMemoryTotalBytes?: number
  /** Die temperature, when a vendor library reported one for this adapter. */
  temperature?: JsTemperatureReading
}

export interface JsGpuEngineSnapshot {
  /** Raw engine type from the counter, e.g. `3d`, `videodecode`. */
  engine: string
  /** Friendlier label for the same engine. */
  label: string
  utilisationPercent: number
}

export interface JsGpuSnapshot {
  adapters: Array<JsGpuAdapterSnapshot>
  /** True when the GPU counter sets could not be registered. */
  unavailable: boolean
}

export interface JsHistoryPoint {
  timestampUnixMs: number
  cpuTimePercent?: number
  cpuUtilityPercent?: number
  cpuBusiestPercent?: number
  memoryUsedBytes?: number
  memoryAvailableBytes?: number
  memoryCommittedBytes?: number
  diskReadBytesPerSecond?: number
  diskWriteBytesPerSecond?: number
  diskActivePercent?: number
  networkDownBytesPerSecond?: number
  networkUpBytesPerSecond?: number
  gpuPercent?: number
  gpuMemoryBytes?: number
  processCount?: number
  threadCount?: number
  handleCount?: number
  /** Peak within the window, which a mean would otherwise hide. */
  cpuTimePeakPercent?: number
  memoryUsedPeakBytes?: number
  diskTotalPeakBytesPerSecond?: number
}

export interface JsHistoryResult {
  points: Array<JsHistoryPoint>
  /** Which retention tier answered the query. */
  tier: number
  /** Nominal resolution of that tier, in milliseconds. */
  resolutionMs: number
  /** False when history is disabled or the database could not be opened. */
  available: boolean
}

export interface JsHistoryTier {
  tier: number
  rowCount: number
}

/** A service a process hosts, by both of its names. */
export interface JsHostedService {
  /** The key name, e.g. `Audiosrv`. */
  name: string
  /** The name people read, e.g. `Windows Audio`. */
  displayName: string
}

export interface JsHostInfo {
  computerName: string
  osName?: string
  osVersion: string
  osBuild?: string
  architecture: string
  isElevated: boolean
  hasDebugPrivilege: boolean
  bootTimeUnixMs?: number
  nativeModuleVersion: string
}

/** The result of asking to run something as administrator. */
export interface JsLaunchOutcome {
  /**
   * `started`, `declined` (the user answered no, which is not a failure)
   * or `failed`, with the Windows error.
   */
  outcome: 'started' | 'declined' | 'failed'
  win32Error?: number
}

export interface JsLogicalProcessorSample {
  index: number
  group: number
  numberInGroup: number
  coreId?: number
  efficiencyClass?: number
  timeUtilizationPercent: number
  dpcPercent: number
  interruptPercent: number
  kernelPercent: number
  userPercent: number
  currentFrequencyMhz?: number
  maxFrequencyMhz?: number
}

export interface JsMemoryDebugGlobal {
  memoryLoadPercent: number
  totalPhysBytes: number
  availPhysBytes: number
  totalPageFileBytes: number
  availPageFileBytes: number
  totalVirtualBytes: number
  availVirtualBytes: number
}

export interface JsMemoryDebugList {
  freeAndZeroBytes: number
  modifiedBytes: number
  modifiedNoWriteBytes: number
  standbyBytes: number
  standbyByPriorityBytes: Array<number>
}

export interface JsMemoryDebugPerformance {
  pageSizeBytes: number
  commitTotalPages: number
  commitLimitPages: number
  commitPeakPages: number
  physicalTotalPages: number
  physicalAvailablePages: number
  systemCachePages: number
  kernelTotalPages: number
  kernelPagedPages: number
  kernelNonpagedPages: number
  handleCount: number
  processCount: number
  threadCount: number
}

export interface JsMemoryDebugSample {
  globalMemoryStatusEx: JsMemoryDebugGlobal
  performanceInformation?: JsMemoryDebugPerformance
  memoryList?: JsMemoryDebugList
  installedPhysicalBytes?: number
}

export interface JsMemorySnapshot {
  installedPhysicalBytes?: number
  totalPhysicalBytes: number
  availablePhysicalBytes: number
  usedPhysicalBytes: number
  physicalUtilizationPercent: number
  memoryLoadPercent: number
  committedBytes?: number
  commitLimitBytes?: number
  commitPeakBytes?: number
  cachedBytes?: number
  standbyBytes?: number
  modifiedBytes?: number
  freeBytes?: number
  pagedPoolBytes?: number
  nonPagedPoolBytes?: number
  pageFileTotalBytes?: number
  pageFileUsedBytes?: number
  pageSizeBytes: number
  debug?: JsMemoryDebugSample
}

export interface JsNetworkInterfaceSnapshot {
  name: string
  receivedBytesPerSecond: number
  sentBytesPerSecond: number
  totalBytesPerSecond: number
  linkSpeedBitsPerSecond?: number
  receivedPacketsPerSecond?: number
  sentPacketsPerSecond?: number
  outboundDiscardsPerSecond?: number
  isLoopback: boolean
}

export interface JsNetworkSnapshot {
  interfaces: Array<JsNetworkInterfaceSnapshot>
  /** Summed over non-loopback interfaces. */
  receivedBytesPerSecond: number
  sentBytesPerSecond: number
  unavailable: boolean
}

export interface JsProcessesSnapshot {
  processes: Array<JsProcessSnapshot>
  totalCount: number
  accessDeniedCount: number
  vanishedCount: number
  collectionDurationMs: number
}

export interface JsProcessSnapshot {
  /** `pid:createTime100ns`. The only safe identity across samples. */
  key: string
  pid: number
  parentPid: number
  parentKey?: string
  name: string
  imagePath?: string
  commandLine?: string
  /** Display only - exceeds the exact integer range of a JS number. */
  createTime100ns: number
  createTimeUnixMs: number
  sessionId: number
  isWow64?: boolean
  architecture?: string
  userName?: string
  isProtected?: boolean
  /** `ProductName` from the image version resource, e.g. "Google Chrome". */
  productName?: string
  /** `CompanyName` from the image version resource. */
  companyName?: string
  /** `FileDescription` from the image version resource. */
  fileDescription?: string
  /** Windows package full name, present only for packaged applications. */
  packageFullName?: string
  /** Application User Model ID, present only for packaged applications. */
  applicationUserModelId?: string
  basePriority: number
  kernelTime100ns: number
  userTime100ns: number
  cpuMachinePercent?: number
  cpuCoreEquivalentPercent?: number
  workingSetBytes: number
  privateWorkingSetBytes: number
  privateCommitBytes: number
  peakWorkingSetBytes: number
  pagedPoolBytes: number
  nonPagedPoolBytes: number
  virtualSizeBytes: number
  pageFaultCount: number
  hardFaultCount: number
  threadCount: number
  handleCount: number
  ioReadBytes: number
  ioWriteBytes: number
  ioOtherBytes: number
  ioReadOperations: number
  ioWriteOperations: number
  ioOtherOperations: number
  ioReadBytesPerSecond?: number
  ioWriteBytesPerSecond?: number
  /**
   * Maximum GPU engine utilisation for this process, 0..100. Absent when the
   * GPU counter set is unavailable or the process used no GPU.
   */
  gpuPercent?: number
  /** Dedicated (on-board) GPU memory attributed to this process. */
  gpuDedicatedMemoryBytes?: number
  /** Shared (system) GPU memory attributed to this process. */
  gpuSharedMemoryBytes?: number
  /**
   * Reason the handle-derived fields are missing, when they are.
   *
   * Declared with an explicit TypeScript union so the generated declaration
   * is as precise as the values we actually emit, and the published types can
   * be checked against it exactly.
   */
  detailFailure?: 'accessDenied' | 'processExited' | 'notSupported' | 'pending'
  /**
   * The Windows services running in this process. Absent for the many
   * processes that host none.
   */
  services?: Array<JsHostedService>
}

/** What the process menu needs to know before it is shown. */
export interface JsProcessState {
  /**
   * `running`, or why the process cannot be reached: `notRunning`,
   * `identityChanged` (the PID now belongs to another process) or
   * `accessDenied` (even reading it is refused).
   */
  status: 'running' | 'notRunning' | 'identityChanged' | 'accessDenied'
  /** Windows would let this application end it. */
  canEnd: boolean
  /**
   * Windows would let this application change its priority, efficiency
   * mode or affinity.
   */
  canAdjust: boolean
  /** Ending it would stop Windows. Absent when that could not be read. */
  isCritical?: boolean
  /** Its windows on the taskbar. */
  windowCount: number
  /** It is the Windows shell: the Explorer that owns the taskbar. */
  isShell: boolean
  /**
   * `idle`, `belowNormal`, `normal`, `aboveNormal`, `high` or `realtime`.
   * Absent when it cannot be read.
   */
  priorityClass?: 'idle' | 'belowNormal' | 'normal' | 'aboveNormal' | 'high' | 'realtime'
  /**
   * Whether it is set to run as EcoQoS, which is what Efficiency mode sets.
   * Absent when that cannot be read.
   */
  efficiencyMode?: boolean
  /** The logical processors it may run on, by index. Absent when unreadable. */
  affinity?: Array<number>
  /** The logical processors the system offers it, by index. */
  processors?: Array<number>
}

/**
 * The result of changing a setting of a process, with what Windows actually
 * applied read back afterwards, since that is not always what was asked for.
 */
export interface JsSettingOutcome {
  outcome: 'done' | 'notRunning' | 'identityChanged' | 'accessDenied' | 'failed'
  win32Error?: number
  priorityClass?: 'idle' | 'belowNormal' | 'normal' | 'aboveNormal' | 'high' | 'realtime'
  efficiencyMode?: boolean
  affinity?: Array<number>
}

/** What became of restarting Windows Explorer. */
export interface JsShellOutcome {
  /**
   * `restarted` (Windows brought the shell back by itself), `started` (it
   * did not, so a new one was started), `notStarted` (it did not, and
   * starting one was not allowed), `noShell` (no shell was running),
   * `accessDenied` or `failed`.
   */
  outcome: 'restarted' | 'started' | 'notStarted' | 'noShell' | 'accessDenied' | 'failed'
  win32Error?: number
}

export interface JsSystemSnapshot {
  sequence: number
  wallClockUnixMs: number
  monotonicMs: number
  intervalMs?: number
  cpu: JsCpuSnapshot
  memory: JsMemorySnapshot
  processes?: JsProcessesSnapshot
  disks: JsDisksSnapshot
  network: JsNetworkSnapshot
  gpu: JsGpuSnapshot
  thermal: JsThermalSnapshot
  diagnostics: JsCollectionDiagnostics
}

export interface JsTemperatureReading {
  celsius: number
  /**
   * The source is what says how much the number can be trusted, so it
   * travels with every reading.
   *
   * Declared with an explicit `ts_type` so the generated declarations carry
   * the same union the published types do. A napi string enum would generate
   * a TypeScript `enum`, and a string literal is not assignable to an enum
   * member, which would break the bidirectional contract check in
   * `native-contract.ts` in one direction only - the worst kind of drift.
   */
  source: 'acpiThermalZone' | 'nvml' | 'storageDevice'
  /**
   * Exactly what reported it - an ACPI zone name, a GPU board name, a drive
   * model. Never a category such as "CPU".
   */
  sensor: string
  /** Where the vendor says throttling begins, when it publishes a threshold. */
  warningCelsius?: number
  /** Where the vendor says the device is in danger, when it publishes one. */
  criticalCelsius?: number
  /**
   * Age of the measurement. Zero for zone counters, read every sample; up to
   * the source's refresh interval for the ones polled more slowly.
   */
  measuredAgoMs: number
}

export interface JsThermalSnapshot {
  /** Every ACPI zone reporting a physically plausible value, hottest first. */
  zones: Array<JsThermalZoneSnapshot>
  /**
   * The hottest zone as a reading. **Not a CPU package temperature**: what an
   * ACPI zone is attached to is defined by the system firmware, so it is
   * always presented under its own zone name.
   */
  primaryZone?: JsTemperatureReading
  /**
   * Every GPU a vendor library reported, whether or not it could be joined to
   * an adapter.
   */
  gpus: Array<JsTemperatureReading>
  /** Every drive that reports a temperature. */
  drives: Array<JsTemperatureReading>
  /**
   * True when the `Thermal Zone Information` counter set is absent, which is
   * normal on a machine whose firmware declares no zones.
   */
  zonesUnavailable: boolean
  /** True when no NVIDIA driver is present. Not an error. */
  nvmlUnavailable: boolean
}

export interface JsThermalZoneSnapshot {
  /** The zone's ACPI name, e.g. `\_TZ.TZ01`. */
  instance: string
  celsius: number
  /** True when the value came from `High Precision Temperature`. */
  highPrecision: boolean
}

/**
 * Start `file` with `parameters` as administrator, through the Windows
 * elevation prompt. Resolves once the user has answered it, which can take as
 * long as they like, so it runs off the JavaScript thread.
 */
export declare function launchElevated(file: string, parameters: string): Promise<JsLaunchOutcome>

/** Confirms the native module loaded and reports its version. */
export declare function nativeProbe(): string

/** The full path of the executable a process is running, when it can be read. */
export declare function processImagePath(pid: number): string | null

/**
 * Ask Windows to restart this application if it crashes or stops responding.
 *
 * `command_line` is what the restarted process receives, so pass a marker the
 * application can recognise. Returns false when Windows refused, which simply
 * means the application will not come back by itself.
 */
export declare function registerForRestart(commandLine: string): boolean

/**
 * Restart the Windows shell: end the Explorer that owns the taskbar, and see
 * that a new one takes its place.
 *
 * Windows restarts the shell by itself when it ends unexpectedly (Winlogon's
 * `AutoRestartShell`, which is on unless someone turned it off). If no shell
 * has appeared after a few seconds, a new Explorer is started - but only when
 * `start_if_missing` is true. The caller passes false when running as
 * administrator, because an Explorer started from an elevated process runs
 * elevated, and so would everything launched from the taskbar afterwards.
 */
export declare function restartShell(startIfMissing: boolean): Promise<JsShellOutcome>

/**
 * Run a command the way Windows' Run dialog does: a program, a document, a
 * folder, a URL or a registered name, with parameters, starting in the user's
 * profile folder. `as_administrator` shows the elevation prompt first.
 */
export declare function runCommand(command: string, asAdministrator: boolean): Promise<JsLaunchOutcome>

/**
 * Turn Efficiency mode on or off, as Windows Task Manager defines it: low
 * priority and EcoQoS on, or both undone.
 *
 * Off hands the power decision back to Windows rather than forcing full speed,
 * and restores `restore_priority` - the class the process had before - or
 * normal when that is not known.
 */
export declare function setEfficiencyMode(key: string, enabled: boolean, restorePriority?: 'idle' | 'belowNormal' | 'normal' | 'aboveNormal' | 'high' | 'realtime'): JsSettingOutcome

/** Restrict a process to the given logical processors, by index. */
export declare function setProcessAffinity(key: string, processors: Array<number>): JsSettingOutcome

/**
 * Set a process's priority class, by name.
 *
 * Windows may apply a different class than asked for - realtime becomes high
 * for a caller without the privilege to raise it that far - so the class in
 * effect afterwards is read back and returned.
 */
export declare function setProcessPriority(key: string, priorityClass: 'idle' | 'belowNormal' | 'normal' | 'aboveNormal' | 'high' | 'realtime'): JsSettingOutcome

/**
 * Show the Windows Properties dialog for a file, as Explorer does.
 *
 * False when Windows could not show it, usually because the file is no longer
 * at that path.
 */
export declare function showFileProperties(path: string): boolean

/**
 * Cancel the restart registration, so a deliberate quit is never mistaken for
 * a crash.
 */
export declare function unregisterForRestart(): boolean
